[config]
schemaVersion = "0.0.1"

[package]
namespace = "andre"
name = "UnifiedStorage"
versionNumber = "1.1.4"
description = "Unified Chest Terminal for Valheim: native chest UI with nearby storage aggregation, search and scroll."
websiteUrl = "https://github.com/Caracioly/UnifiedStorage"
containsNsfwContent = false
[package.dependencies]
denikson-BepInExPack_Valheim = "5.4.2202"
ValheimModding-Jotunn = "2.27.1"


[build]
icon = "./icon.png"
readme = "./README.md"
outdir = "./build"

[[build.copy]]
source = "./dist/UnifiedStorage-1.1.4/plugins"
target = "/plugins"


[publish]
repository = "https://thunderstore.io"
communities = [ "valheim", ]

[publish.categories]
valheim = [ "mods", ]
